root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include = ["*.go"]
  exclude = ["assets", "tmp", "vendor"]

[log]
  time = "2000-01-01 00:00:00"
  level = "debug"