FROM postgres:15.2

COPY ./init.sql /docker-entrypoint-initdb.d/

COPY postgresql.conf /etc/postgresql/postgresql.conf

ENV POSTGRES_DB=test \
    POSTGRES_USER=user \
    POSTGRES_PASSWORD=password

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
